import { ComponentDefinition, ComponentType } from '@/types'

export const COMPONENT_CATEGORIES: { type: ComponentType; label: string; icon: string }[] = [
  { type: 'navigation', label: 'Navigatie', icon: 'Menu' },
  { type: 'hero', label: 'Hero', icon: 'Zap' },
  { type: 'features', label: 'Features', icon: 'Grid3x3' },
  { type: 'stats', label: 'Stats', icon: 'BarChart2' },
  { type: 'testimonials', label: 'Testimonials', icon: 'MessageSquare' },
  { type: 'pricing', label: 'Pricing', icon: 'Tag' },
  { type: 'cta', label: 'CTA', icon: 'MousePointer' },
  { type: 'portfolio', label: 'Portfolio', icon: 'Image' },
  { type: 'team', label: 'Team', icon: 'Users' },
  { type: 'blog', label: 'Blog', icon: 'BookOpen' },
  { type: 'faq', label: 'FAQ', icon: 'HelpCircle' },
  { type: 'contact', label: 'Contact', icon: 'Mail' },
  { type: 'footer', label: 'Footer', icon: 'PanelBottom' },
  { type: 'restaurant', label: 'Restaurant', icon: 'UtensilsCrossed' },
  { type: 'hotel', label: 'Hotel', icon: 'BedDouble' },
  { type: 'marketplace', label: 'Marketplace', icon: 'ShoppingBag' },
]

export const COMPONENTS: ComponentDefinition[] = [
  // Navigation
  {
    type: 'navigation',
    variant: 'simple',
    label: 'Eenvoudige nav',
    description: 'Logo links, links rechts, CTA knop',
    fields: [
      { key: 'logo', label: 'Logo tekst', type: 'text', placeholder: 'Bedrijfsnaam' },
      { key: 'cta', label: 'CTA knop', type: 'text', placeholder: 'Contact' },
    ],
  },
  {
    type: 'navigation',
    variant: 'centered',
    label: 'Gecentreerde nav',
    description: 'Logo boven, links gecentreerd',
    fields: [
      { key: 'logo', label: 'Logo tekst', type: 'text', placeholder: 'Bedrijfsnaam' },
    ],
  },
  {
    type: 'navigation',
    variant: 'mega',
    label: 'Mega menu nav',
    description: 'Nav met dropdown categorieën',
    fields: [
      { key: 'logo', label: 'Logo tekst', type: 'text', placeholder: 'Bedrijfsnaam' },
      { key: 'cta', label: 'CTA knop', type: 'text', placeholder: 'Gratis proberen' },
    ],
  },
  {
    type: 'navigation',
    variant: 'announcement',
    label: 'Announcement nav',
    description: 'Blauwe annoncementbalk + login/signup',
    fields: [
      { key: 'logo', label: 'Logo tekst', type: 'text', placeholder: 'Bedrijfsnaam' },
      { key: 'announcement', label: 'Aankondiging', type: 'text', placeholder: '🎉 Nieuw: bekijk onze laatste features' },
      { key: 'badge', label: 'Badge tekst', type: 'text', placeholder: 'New' },
      { key: 'login', label: 'Login knop', type: 'text', placeholder: 'Login' },
      { key: 'cta', label: 'CTA knop', type: 'text', placeholder: 'Aanmelden' },
    ],
  },
  {
    type: 'navigation',
    variant: 'search',
    label: 'Nav met zoekbalk',
    description: 'Navigatie met zoekbalk in het midden',
    fields: [
      { key: 'logo', label: 'Logo tekst', type: 'text', placeholder: 'Bedrijfsnaam' },
      { key: 'cta', label: 'CTA knop', type: 'text', placeholder: 'Aanmelden' },
    ],
  },
  {
    type: 'navigation',
    variant: 'dark',
    label: 'Donkere nav',
    description: 'Donkere achtergrond navigatie',
    fields: [
      { key: 'logo', label: 'Logo tekst', type: 'text', placeholder: 'Bedrijfsnaam' },
      { key: 'cta', label: 'CTA knop', type: 'text', placeholder: 'Aan de slag' },
    ],
  },
  {
    type: 'navigation',
    variant: 'transparent',
    label: 'Transparante nav',
    description: 'Overlay navigatie op hero-afbeelding',
    fields: [
      { key: 'logo', label: 'Logo tekst', type: 'text', placeholder: 'Bedrijfsnaam' },
      { key: 'cta', label: 'CTA knop', type: 'text', placeholder: 'Boek nu' },
    ],
  },

  // Hero
  {
    type: 'hero',
    variant: 'centered',
    label: 'Gecentreerde hero',
    description: 'Titel, subtitel en knoppen gecentreerd',
    fields: [
      { key: 'eyebrow', label: 'Eyebrow tekst', type: 'text', placeholder: 'Nieuw' },
      { key: 'title', label: 'Titel', type: 'textarea', placeholder: 'De beste oplossing voor jouw bedrijf' },
      { key: 'subtitle', label: 'Subtitel', type: 'textarea', placeholder: 'Beschrijf hier kort wat je doet en welke waarde je biedt.' },
      { key: 'cta_primary', label: 'Primaire knop', type: 'text', placeholder: 'Aan de slag' },
      { key: 'cta_secondary', label: 'Secundaire knop', type: 'text', placeholder: 'Meer info' },
    ],
  },
  {
    type: 'hero',
    variant: 'split',
    label: 'Split hero',
    description: 'Tekst links, afbeelding rechts',
    fields: [
      { key: 'title', label: 'Titel', type: 'textarea', placeholder: 'Jouw titel hier' },
      { key: 'subtitle', label: 'Subtitel', type: 'textarea', placeholder: 'Korte beschrijving van je dienst of product.' },
      { key: 'cta_primary', label: 'Primaire knop', type: 'text', placeholder: 'Aan de slag' },
      { key: 'cta_secondary', label: 'Secundaire knop', type: 'text', placeholder: 'Demo bekijken' },
    ],
  },
  {
    type: 'hero',
    variant: 'video',
    label: 'Video hero',
    description: 'Hero met video placeholder achtergrond',
    fields: [
      { key: 'title', label: 'Titel', type: 'textarea', placeholder: 'Indrukwekkende titel' },
      { key: 'cta_primary', label: 'Primaire knop', type: 'text', placeholder: 'Video bekijken' },
    ],
  },
  {
    type: 'hero',
    variant: 'minimal',
    label: 'Minimale hero',
    description: 'Grote typografie, geen afbeelding',
    fields: [
      { key: 'title', label: 'Titel', type: 'textarea', placeholder: 'Wij maken geweldige websites' },
      { key: 'cta_primary', label: 'Knop', type: 'text', placeholder: 'Bekijk ons werk' },
    ],
  },
  {
    type: 'hero',
    variant: 'fullscreen',
    label: 'Fullscreen hero',
    description: 'Afbeelding met gradient overlay en tekst',
    fields: [
      { key: 'title', label: 'Titel', type: 'textarea', placeholder: 'Ontdek de mogelijkheden' },
      { key: 'subtitle', label: 'Subtitel', type: 'text', placeholder: 'Jouw verhaal begint hier.' },
      { key: 'cta_primary', label: 'Primaire knop', type: 'text', placeholder: 'Meer ontdekken' },
    ],
  },
  {
    type: 'hero',
    variant: 'dark-split',
    label: 'Dark split hero',
    description: 'Donkere linkerkant, afbeelding rechts',
    fields: [
      { key: 'title', label: 'Titel', type: 'textarea', placeholder: 'Krachtige oplossingen voor jouw bedrijf' },
      { key: 'subtitle', label: 'Subtitel', type: 'textarea', placeholder: 'Beschrijf hier je kernboodschap.' },
      { key: 'cta_primary', label: 'Primaire knop', type: 'text', placeholder: 'Aan de slag' },
      { key: 'cta_secondary', label: 'Secundaire knop', type: 'text', placeholder: 'Demo bekijken' },
    ],
  },
  {
    type: 'hero',
    variant: 'availability',
    label: 'Availability hero',
    description: 'Booking bar over hero-afbeelding (hotel/restaurant)',
    fields: [
      { key: 'title', label: 'Titel', type: 'textarea', placeholder: 'Welkom in ons hotel' },
      { key: 'cta_primary', label: 'Boek knop', type: 'text', placeholder: 'Beschikbaarheid controleren' },
    ],
  },
  {
    type: 'hero',
    variant: 'newsletter',
    label: 'Newsletter hero',
    description: 'Email capture hero gecentreerd',
    fields: [
      { key: 'title', label: 'Titel', type: 'textarea', placeholder: 'Blijf op de hoogte' },
      { key: 'subtitle', label: 'Subtitel', type: 'text', placeholder: 'Ontvang wekelijks de laatste nieuwtjes.' },
      { key: 'cta_primary', label: 'Knop tekst', type: 'text', placeholder: 'Inschrijven' },
    ],
  },
  {
    type: 'hero',
    variant: 'social-proof',
    label: 'Social proof hero',
    description: 'Hero met avatars en sterren beoordeling',
    fields: [
      { key: 'title', label: 'Titel', type: 'textarea', placeholder: 'Vertrouwd door duizenden klanten' },
      { key: 'subtitle', label: 'Subtitel', type: 'textarea', placeholder: 'Sluit je aan bij de groeiende community.' },
      { key: 'cta_primary', label: 'Primaire knop', type: 'text', placeholder: 'Gratis proberen' },
      { key: 'social_proof_text', label: 'Social proof tekst', type: 'text', placeholder: '2.000+ tevreden klanten' },
    ],
  },

  // Features
  {
    type: 'features',
    variant: 'grid-3',
    label: 'Features 3-kolommen',
    description: '3 features met icoon, titel en tekst',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Waarom kiezen voor ons?' },
      { key: 'f1_title', label: 'Feature 1 titel', type: 'text', placeholder: 'Snel & betrouwbaar', group: 'Feature 1' },
      { key: 'f1_desc', label: 'Feature 1 tekst', type: 'textarea', placeholder: 'Korte omschrijving van deze feature.', group: 'Feature 1' },
      { key: 'f2_title', label: 'Feature 2 titel', type: 'text', placeholder: 'Eenvoudig te gebruiken', group: 'Feature 2' },
      { key: 'f2_desc', label: 'Feature 2 tekst', type: 'textarea', placeholder: 'Korte omschrijving van deze feature.', group: 'Feature 2' },
      { key: 'f3_title', label: 'Feature 3 titel', type: 'text', placeholder: 'Altijd beschikbaar', group: 'Feature 3' },
      { key: 'f3_desc', label: 'Feature 3 tekst', type: 'textarea', placeholder: 'Korte omschrijving van deze feature.', group: 'Feature 3' },
    ],
  },
  {
    type: 'features',
    variant: 'list-split',
    label: 'Features lijst split',
    description: 'Tekst links, feature lijst rechts',
    fields: [
      { key: 'title', label: 'Titel', type: 'textarea', placeholder: 'Alles wat je nodig hebt' },
      { key: 'subtitle', label: 'Subtitel', type: 'textarea', placeholder: 'Een korte beschrijving van je aanbod.' },
    ],
  },
  {
    type: 'features',
    variant: 'alternating',
    label: 'Afwisselende features',
    description: 'Features afwisselend links/rechts',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Hoe het werkt' },
      { key: 'f1_title', label: 'Stap 1 titel', type: 'text', placeholder: 'Stap 1', group: 'Stap 1' },
      { key: 'f1_desc', label: 'Stap 1 tekst', type: 'textarea', placeholder: 'Beschrijving van stap 1.', group: 'Stap 1' },
      { key: 'f2_title', label: 'Stap 2 titel', type: 'text', placeholder: 'Stap 2', group: 'Stap 2' },
      { key: 'f2_desc', label: 'Stap 2 tekst', type: 'textarea', placeholder: 'Beschrijving van stap 2.', group: 'Stap 2' },
    ],
  },
  {
    type: 'features',
    variant: 'grid-4',
    label: 'Features 4-kolommen',
    description: '4 features in een raster',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Alles wat je nodig hebt' },
      { key: 'f1_title', label: 'Feature 1 titel', type: 'text', placeholder: 'Snel', group: 'Feature 1' },
      { key: 'f1_desc', label: 'Feature 1 tekst', type: 'textarea', placeholder: 'Korte beschrijving.', group: 'Feature 1' },
      { key: 'f2_title', label: 'Feature 2 titel', type: 'text', placeholder: 'Betrouwbaar', group: 'Feature 2' },
      { key: 'f2_desc', label: 'Feature 2 tekst', type: 'textarea', placeholder: 'Korte beschrijving.', group: 'Feature 2' },
      { key: 'f3_title', label: 'Feature 3 titel', type: 'text', placeholder: 'Schaalbaar', group: 'Feature 3' },
      { key: 'f3_desc', label: 'Feature 3 tekst', type: 'textarea', placeholder: 'Korte beschrijving.', group: 'Feature 3' },
      { key: 'f4_title', label: 'Feature 4 titel', type: 'text', placeholder: 'Veilig', group: 'Feature 4' },
      { key: 'f4_desc', label: 'Feature 4 tekst', type: 'textarea', placeholder: 'Korte beschrijving.', group: 'Feature 4' },
    ],
  },
  {
    type: 'features',
    variant: 'numbered',
    label: 'Genummerde features',
    description: 'Grote nummers (01 02 03) met tekst',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Hoe het werkt' },
      { key: 'f1_title', label: 'Stap 1 titel', type: 'text', placeholder: 'Aanmelden', group: 'Stap 1' },
      { key: 'f1_desc', label: 'Stap 1 tekst', type: 'textarea', placeholder: 'Maak gratis een account aan.', group: 'Stap 1' },
      { key: 'f2_title', label: 'Stap 2 titel', type: 'text', placeholder: 'Instellen', group: 'Stap 2' },
      { key: 'f2_desc', label: 'Stap 2 tekst', type: 'textarea', placeholder: 'Configureer je omgeving.', group: 'Stap 2' },
      { key: 'f3_title', label: 'Stap 3 titel', type: 'text', placeholder: 'Lanceren', group: 'Stap 3' },
      { key: 'f3_desc', label: 'Stap 3 tekst', type: 'textarea', placeholder: 'Ga live en groei.', group: 'Stap 3' },
    ],
  },
  {
    type: 'features',
    variant: 'timeline',
    label: 'Timeline features',
    description: 'Genummerde stappen met verbindingslijn',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Ons proces' },
      { key: 'subtitle', label: 'Subtitel', type: 'text', placeholder: 'Stap voor stap naar resultaat.' },
      { key: 'f1_title', label: 'Stap 1 titel', type: 'text', placeholder: 'Intake', group: 'Stap 1' },
      { key: 'f1_desc', label: 'Stap 1 tekst', type: 'textarea', placeholder: 'We leren je kennen.', group: 'Stap 1' },
      { key: 'f2_title', label: 'Stap 2 titel', type: 'text', placeholder: 'Ontwerp', group: 'Stap 2' },
      { key: 'f2_desc', label: 'Stap 2 tekst', type: 'textarea', placeholder: 'We bouwen een wireframe.', group: 'Stap 2' },
      { key: 'f3_title', label: 'Stap 3 titel', type: 'text', placeholder: 'Bouw', group: 'Stap 3' },
      { key: 'f3_desc', label: 'Stap 3 tekst', type: 'textarea', placeholder: 'We ontwikkelen het product.', group: 'Stap 3' },
      { key: 'f4_title', label: 'Stap 4 titel', type: 'text', placeholder: 'Lancering', group: 'Stap 4' },
      { key: 'f4_desc', label: 'Stap 4 tekst', type: 'textarea', placeholder: 'We gaan live samen.', group: 'Stap 4' },
    ],
  },
  {
    type: 'features',
    variant: 'dark',
    label: 'Donkere features',
    description: 'Donkere achtergrond met glassmorphism kaarten',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Krachtige features' },
      { key: 'subtitle', label: 'Subtitel', type: 'text', placeholder: 'Alles in één platform.' },
      { key: 'cta', label: 'Knop tekst', type: 'text', placeholder: 'Alle features' },
      { key: 'f1_title', label: 'Feature 1 titel', type: 'text', placeholder: 'Feature 1', group: 'Feature 1' },
      { key: 'f1_desc', label: 'Feature 1 tekst', type: 'textarea', placeholder: 'Korte beschrijving.', group: 'Feature 1' },
      { key: 'f2_title', label: 'Feature 2 titel', type: 'text', placeholder: 'Feature 2', group: 'Feature 2' },
      { key: 'f2_desc', label: 'Feature 2 tekst', type: 'textarea', placeholder: 'Korte beschrijving.', group: 'Feature 2' },
      { key: 'f3_title', label: 'Feature 3 titel', type: 'text', placeholder: 'Feature 3', group: 'Feature 3' },
      { key: 'f3_desc', label: 'Feature 3 tekst', type: 'textarea', placeholder: 'Korte beschrijving.', group: 'Feature 3' },
    ],
  },

  // Stats
  {
    type: 'stats',
    variant: 'simple-4',
    label: '4 statistieken',
    description: 'Rij met 4 nummers en labels',
    fields: [
      { key: 's1_num', label: 'Stat 1 getal', type: 'text', placeholder: '10.000+', group: 'Stat 1' },
      { key: 's1_label', label: 'Stat 1 label', type: 'text', placeholder: 'Klanten', group: 'Stat 1' },
      { key: 's2_num', label: 'Stat 2 getal', type: 'text', placeholder: '99%', group: 'Stat 2' },
      { key: 's2_label', label: 'Stat 2 label', type: 'text', placeholder: 'Tevredenheid', group: 'Stat 2' },
      { key: 's3_num', label: 'Stat 3 getal', type: 'text', placeholder: '50+', group: 'Stat 3' },
      { key: 's3_label', label: 'Stat 3 label', type: 'text', placeholder: 'Landen', group: 'Stat 3' },
      { key: 's4_num', label: 'Stat 4 getal', type: 'text', placeholder: '24/7', group: 'Stat 4' },
      { key: 's4_label', label: 'Stat 4 label', type: 'text', placeholder: 'Support', group: 'Stat 4' },
    ],
  },

  {
    type: 'stats',
    variant: 'icons',
    label: 'Stats met iconen',
    description: 'Statistieken met icoon en beschrijving',
    fields: [
      { key: 's1_num', label: 'Stat 1 getal', type: 'text', placeholder: '10.000+', group: 'Stat 1' },
      { key: 's1_label', label: 'Stat 1 label', type: 'text', placeholder: 'Klanten', group: 'Stat 1' },
      { key: 's1_desc', label: 'Stat 1 beschrijving', type: 'text', placeholder: 'Wereldwijd tevreden gebruikers', group: 'Stat 1' },
      { key: 's2_num', label: 'Stat 2 getal', type: 'text', placeholder: '99%', group: 'Stat 2' },
      { key: 's2_label', label: 'Stat 2 label', type: 'text', placeholder: 'Tevredenheid', group: 'Stat 2' },
      { key: 's2_desc', label: 'Stat 2 beschrijving', type: 'text', placeholder: 'Aanbevolen door gebruikers', group: 'Stat 2' },
      { key: 's3_num', label: 'Stat 3 getal', type: 'text', placeholder: '50+', group: 'Stat 3' },
      { key: 's3_label', label: 'Stat 3 label', type: 'text', placeholder: 'Landen', group: 'Stat 3' },
      { key: 's3_desc', label: 'Stat 3 beschrijving', type: 'text', placeholder: 'Wereldwijde aanwezigheid', group: 'Stat 3' },
      { key: 's4_num', label: 'Stat 4 getal', type: 'text', placeholder: '24/7', group: 'Stat 4' },
      { key: 's4_label', label: 'Stat 4 label', type: 'text', placeholder: 'Support', group: 'Stat 4' },
      { key: 's4_desc', label: 'Stat 4 beschrijving', type: 'text', placeholder: 'Altijd bereikbaar', group: 'Stat 4' },
    ],
  },
  {
    type: 'stats',
    variant: 'dark',
    label: 'Donkere stats',
    description: 'Statistieken op donkere achtergrond',
    fields: [
      { key: 's1_num', label: 'Stat 1 getal', type: 'text', placeholder: '10.000+' },
      { key: 's1_label', label: 'Stat 1 label', type: 'text', placeholder: 'Klanten' },
      { key: 's2_num', label: 'Stat 2 getal', type: 'text', placeholder: '99%' },
      { key: 's2_label', label: 'Stat 2 label', type: 'text', placeholder: 'Tevredenheid' },
      { key: 's3_num', label: 'Stat 3 getal', type: 'text', placeholder: '50+' },
      { key: 's3_label', label: 'Stat 3 label', type: 'text', placeholder: 'Landen' },
      { key: 's4_num', label: 'Stat 4 getal', type: 'text', placeholder: '24/7' },
      { key: 's4_label', label: 'Stat 4 label', type: 'text', placeholder: 'Support' },
    ],
  },
  {
    type: 'stats',
    variant: 'progress',
    label: 'Stats met voortgangsbalk',
    description: 'Horizontale voortgangsbalken per statistiek',
    fields: [
      { key: 's1_label', label: 'Stat 1 label', type: 'text', placeholder: 'Klanttevredenheid', group: 'Stat 1' },
      { key: 's1_num', label: 'Stat 1 percentage', type: 'text', placeholder: '98%', group: 'Stat 1' },
      { key: 's2_label', label: 'Stat 2 label', type: 'text', placeholder: 'Projectsucces', group: 'Stat 2' },
      { key: 's2_num', label: 'Stat 2 percentage', type: 'text', placeholder: '95%', group: 'Stat 2' },
      { key: 's3_label', label: 'Stat 3 label', type: 'text', placeholder: 'Op tijd geleverd', group: 'Stat 3' },
      { key: 's3_num', label: 'Stat 3 percentage', type: 'text', placeholder: '92%', group: 'Stat 3' },
    ],
  },

  // Testimonials
  {
    type: 'testimonials',
    variant: 'grid-3',
    label: 'Testimonials 3-kolommen',
    description: '3 reviews met avatar en naam',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Wat onze klanten zeggen' },
      { key: 't1_text', label: 'Review 1', type: 'textarea', placeholder: 'Super tevreden met de service!', group: 'Review 1' },
      { key: 't1_name', label: 'Naam 1', type: 'text', placeholder: 'Jan Janssen', group: 'Review 1' },
      { key: 't1_role', label: 'Functie 1', type: 'text', placeholder: 'CEO, Bedrijf X', group: 'Review 1' },
      { key: 't2_text', label: 'Review 2', type: 'textarea', placeholder: 'Aanrader voor iedereen.', group: 'Review 2' },
      { key: 't2_name', label: 'Naam 2', type: 'text', placeholder: 'Marie Pieters', group: 'Review 2' },
      { key: 't2_role', label: 'Functie 2', type: 'text', placeholder: 'Marketing Manager', group: 'Review 2' },
      { key: 't3_text', label: 'Review 3', type: 'textarea', placeholder: 'Uitstekende kwaliteit.', group: 'Review 3' },
      { key: 't3_name', label: 'Naam 3', type: 'text', placeholder: 'Tom Claes', group: 'Review 3' },
      { key: 't3_role', label: 'Functie 3', type: 'text', placeholder: 'Designer', group: 'Review 3' },
    ],
  },
  {
    type: 'testimonials',
    variant: 'featured',
    label: 'Featured testimonial',
    description: 'Grote enkele quote',
    fields: [
      { key: 'quote', label: 'Quote', type: 'textarea', placeholder: 'Dit is de beste service die we ooit hebben gebruikt.' },
      { key: 'name', label: 'Naam', type: 'text', placeholder: 'Jan Janssen' },
      { key: 'role', label: 'Functie', type: 'text', placeholder: 'CEO, Bedrijf X' },
    ],
  },
  {
    type: 'testimonials',
    variant: 'logos',
    label: 'Logo strip',
    description: 'Klantlogo\'s als social proof balk',
    fields: [
      { key: 'title', label: 'Boven tekst', type: 'text', placeholder: 'Vertrouwd door toonaangevende bedrijven' },
    ],
  },
  {
    type: 'testimonials',
    variant: 'dark',
    label: 'Donkere testimonials',
    description: 'Donkere achtergrond, 2-kolom met aanhalingstekens',
    fields: [
      { key: 't1_text', label: 'Quote 1', type: 'textarea', placeholder: 'Geweldige ervaring met dit team.', group: 'Quote 1' },
      { key: 't1_name', label: 'Naam 1', type: 'text', placeholder: 'Jan Janssen', group: 'Quote 1' },
      { key: 't1_role', label: 'Functie 1', type: 'text', placeholder: 'CEO, Bedrijf', group: 'Quote 1' },
      { key: 't2_text', label: 'Quote 2', type: 'textarea', placeholder: 'Zou het iedereen aanraden.', group: 'Quote 2' },
      { key: 't2_name', label: 'Naam 2', type: 'text', placeholder: 'Marie Pieters', group: 'Quote 2' },
      { key: 't2_role', label: 'Functie 2', type: 'text', placeholder: 'Marketingmanager', group: 'Quote 2' },
    ],
  },

  // Pricing
  {
    type: 'pricing',
    variant: 'three-tiers',
    label: '3 prijsplannen',
    description: 'Starter, Pro en Enterprise',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Eenvoudige prijzen' },
      { key: 'p1_name', label: 'Plan 1 naam', type: 'text', placeholder: 'Starter', group: 'Plan 1' },
      { key: 'p1_price', label: 'Plan 1 prijs', type: 'text', placeholder: '€29/maand', group: 'Plan 1' },
      { key: 'p1_cta', label: 'Plan 1 knop', type: 'text', placeholder: 'Selecteren', group: 'Plan 1' },
      { key: 'p2_name', label: 'Plan 2 naam', type: 'text', placeholder: 'Pro', group: 'Plan 2' },
      { key: 'p2_price', label: 'Plan 2 prijs', type: 'text', placeholder: '€79/maand', group: 'Plan 2' },
      { key: 'p2_cta', label: 'Plan 2 knop', type: 'text', placeholder: 'Aan de slag', group: 'Plan 2' },
      { key: 'p3_name', label: 'Plan 3 naam', type: 'text', placeholder: 'Enterprise', group: 'Plan 3' },
      { key: 'p3_price', label: 'Plan 3 prijs', type: 'text', placeholder: 'Op aanvraag', group: 'Plan 3' },
      { key: 'p3_cta', label: 'Plan 3 knop', type: 'text', placeholder: 'Selecteren', group: 'Plan 3' },
    ],
  },

  {
    type: 'pricing',
    variant: 'table',
    label: 'Vergelijkingstabel',
    description: 'Feature vergelijking per plan met checkmarks',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Vergelijk plannen' },
      { key: 'p1_name', label: 'Plan 1 naam', type: 'text', placeholder: 'Starter', group: 'Plan 1' },
      { key: 'p1_price', label: 'Plan 1 prijs', type: 'text', placeholder: '€29/maand', group: 'Plan 1' },
      { key: 'p2_name', label: 'Plan 2 naam', type: 'text', placeholder: 'Pro', group: 'Plan 2' },
      { key: 'p2_price', label: 'Plan 2 prijs', type: 'text', placeholder: '€79/maand', group: 'Plan 2' },
      { key: 'p3_name', label: 'Plan 3 naam', type: 'text', placeholder: 'Enterprise', group: 'Plan 3' },
      { key: 'p3_price', label: 'Plan 3 prijs', type: 'text', placeholder: 'Op aanvraag', group: 'Plan 3' },
    ],
  },
  {
    type: 'pricing',
    variant: 'packages',
    label: 'Dienst pakketten',
    description: 'Pakketten met afbeelding, prijs en boekknop',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Onze pakketten' },
      { key: 'subtitle', label: 'Subtitel', type: 'text', placeholder: 'Kies het pakket dat bij jou past.' },
      { key: 'p1_name', label: 'Pakket 1 naam', type: 'text', placeholder: 'Basis pakket', group: 'Pakket 1' },
      { key: 'p1_price', label: 'Pakket 1 prijs', type: 'text', placeholder: '€45', group: 'Pakket 1' },
      { key: 'p1_cta', label: 'Pakket 1 knop', type: 'text', placeholder: 'Boek', group: 'Pakket 1' },
      { key: 'p2_name', label: 'Pakket 2 naam', type: 'text', placeholder: 'Standaard pakket', group: 'Pakket 2' },
      { key: 'p2_price', label: 'Pakket 2 prijs', type: 'text', placeholder: '€95', group: 'Pakket 2' },
      { key: 'p2_cta', label: 'Pakket 2 knop', type: 'text', placeholder: 'Boek', group: 'Pakket 2' },
      { key: 'p3_name', label: 'Pakket 3 naam', type: 'text', placeholder: 'Premium pakket', group: 'Pakket 3' },
      { key: 'p3_price', label: 'Pakket 3 prijs', type: 'text', placeholder: '€149', group: 'Pakket 3' },
      { key: 'p3_cta', label: 'Pakket 3 knop', type: 'text', placeholder: 'Boek', group: 'Pakket 3' },
    ],
  },

  // CTA
  {
    type: 'cta',
    variant: 'centered',
    label: 'Gecentreerde CTA',
    description: 'Titel, tekst en knoppen gecentreerd',
    fields: [
      { key: 'title', label: 'Titel', type: 'textarea', placeholder: 'Klaar om te beginnen?' },
      { key: 'subtitle', label: 'Subtitel', type: 'text', placeholder: 'Start vandaag gratis.' },
      { key: 'cta_primary', label: 'Primaire knop', type: 'text', placeholder: 'Gratis starten' },
      { key: 'cta_secondary', label: 'Secundaire knop', type: 'text', placeholder: 'Demo aanvragen' },
    ],
  },
  {
    type: 'cta',
    variant: 'split',
    label: 'Split CTA',
    description: 'Lichtblauwe linkerkant met tekst, afbeelding rechts',
    fields: [
      { key: 'title', label: 'Titel', type: 'textarea', placeholder: 'Klaar om te starten?' },
      { key: 'subtitle', label: 'Subtitel', type: 'textarea', placeholder: 'Neem vandaag nog contact op.' },
      { key: 'cta_primary', label: 'Primaire knop', type: 'text', placeholder: 'Aan de slag' },
      { key: 'cta_secondary', label: 'Secundaire knop', type: 'text', placeholder: 'Meer info' },
    ],
  },
  {
    type: 'cta',
    variant: 'newsletter',
    label: 'Newsletter CTA',
    description: 'Donkere achtergrond met email capture, twee kolommen',
    fields: [
      { key: 'title', label: 'Titel', type: 'textarea', placeholder: 'Schrijf je in voor onze nieuwsbrief' },
      { key: 'subtitle', label: 'Subtitel', type: 'text', placeholder: 'Wekelijks het laatste nieuws.' },
      { key: 'cta', label: 'Knop tekst', type: 'text', placeholder: 'Inschrijven' },
      { key: 'privacy', label: 'Privacy tekst', type: 'text', placeholder: 'Geen spam. Uitschrijven kan altijd.' },
    ],
  },
  {
    type: 'cta',
    variant: 'phone',
    label: 'Telefoon CTA',
    description: 'Prominent telefoonnummer met icoon',
    fields: [
      { key: 'title', label: 'Titel', type: 'text', placeholder: 'Bel ons direct' },
      { key: 'phone', label: 'Telefoonnummer', type: 'text', placeholder: '+32 000 00 00 00' },
      { key: 'subtitle', label: 'Ondertitel', type: 'text', placeholder: 'Bereikbaar van ma-vr 9u-17u' },
    ],
  },
  {
    type: 'cta',
    variant: 'strip',
    label: 'Strip CTA',
    description: 'Compacte balk met icoon, tekst en knoppen',
    fields: [
      { key: 'title', label: 'Titel', type: 'text', placeholder: 'Interesse? Neem contact op.' },
      { key: 'cta_primary', label: 'Primaire knop', type: 'text', placeholder: 'Contact' },
      { key: 'cta_secondary', label: 'Secundaire knop', type: 'text', placeholder: 'Meer info' },
    ],
  },
  {
    type: 'cta',
    variant: 'banner',
    label: 'CTA banner',
    description: 'Volle breedte blauwe banner',
    fields: [
      { key: 'title', label: 'Titel', type: 'text', placeholder: 'Neem contact op' },
      { key: 'cta', label: 'Knop tekst', type: 'text', placeholder: 'Contact' },
    ],
  },

  // Portfolio
  {
    type: 'portfolio',
    variant: 'grid-3',
    label: 'Portfolio 3-kolommen',
    description: '3 projectkaarten met afbeelding',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Ons werk' },
      { key: 'p1_title', label: 'Project 1 titel', type: 'text', placeholder: 'Project naam', group: 'Project 1' },
      { key: 'p1_cat', label: 'Project 1 categorie', type: 'text', placeholder: 'Webdesign', group: 'Project 1' },
      { key: 'p2_title', label: 'Project 2 titel', type: 'text', placeholder: 'Project naam', group: 'Project 2' },
      { key: 'p2_cat', label: 'Project 2 categorie', type: 'text', placeholder: 'Branding', group: 'Project 2' },
      { key: 'p3_title', label: 'Project 3 titel', type: 'text', placeholder: 'Project naam', group: 'Project 3' },
      { key: 'p3_cat', label: 'Project 3 categorie', type: 'text', placeholder: 'Development', group: 'Project 3' },
    ],
  },

  // Team
  {
    type: 'team',
    variant: 'founder',
    label: 'Founder + team',
    description: 'Uitgelichte founder kaart + teamgrid',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Het team achter het bedrijf' },
      { key: 'founder_name', label: 'Founder naam', type: 'text', placeholder: 'Jan Janssen', group: 'Founder' },
      { key: 'founder_role', label: 'Founder functie', type: 'text', placeholder: 'CEO & Founder', group: 'Founder' },
      { key: 'founder_bio', label: 'Founder bio', type: 'textarea', placeholder: 'Korte introductie over de founder.', group: 'Founder' },
    ],
  },
  {
    type: 'team',
    variant: 'list',
    label: 'Team lijst',
    description: 'Horizontale lijst met bio en social iconen',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Maak kennis met ons team' },
      { key: 'm1_name', label: 'Lid 1 naam', type: 'text', placeholder: 'Jan Janssen', group: 'Lid 1' },
      { key: 'm1_role', label: 'Lid 1 functie', type: 'text', placeholder: 'CEO & Founder', group: 'Lid 1' },
      { key: 'm2_name', label: 'Lid 2 naam', type: 'text', placeholder: 'Marie Pieters', group: 'Lid 2' },
      { key: 'm2_role', label: 'Lid 2 functie', type: 'text', placeholder: 'Designer', group: 'Lid 2' },
      { key: 'm3_name', label: 'Lid 3 naam', type: 'text', placeholder: 'Tom Claes', group: 'Lid 3' },
      { key: 'm3_role', label: 'Lid 3 functie', type: 'text', placeholder: 'Developer', group: 'Lid 3' },
    ],
  },
  {
    type: 'team',
    variant: 'grid',
    label: 'Team grid',
    description: 'Teamleden met foto, naam en functie',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Ons team' },
      { key: 'm1_name', label: 'Lid 1 naam', type: 'text', placeholder: 'Jan Janssen', group: 'Lid 1' },
      { key: 'm1_role', label: 'Lid 1 functie', type: 'text', placeholder: 'CEO & Founder', group: 'Lid 1' },
      { key: 'm2_name', label: 'Lid 2 naam', type: 'text', placeholder: 'Marie Pieters', group: 'Lid 2' },
      { key: 'm2_role', label: 'Lid 2 functie', type: 'text', placeholder: 'Designer', group: 'Lid 2' },
      { key: 'm3_name', label: 'Lid 3 naam', type: 'text', placeholder: 'Tom Claes', group: 'Lid 3' },
      { key: 'm3_role', label: 'Lid 3 functie', type: 'text', placeholder: 'Developer', group: 'Lid 3' },
    ],
  },

  // Blog
  {
    type: 'blog',
    variant: 'grid-3',
    label: 'Blog 3-kolommen',
    description: '3 blogartikel kaarten',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Laatste artikelen' },
      { key: 'a1_title', label: 'Artikel 1 titel', type: 'text', placeholder: 'Hoe je een website bouwt', group: 'Artikel 1' },
      { key: 'a1_date', label: 'Artikel 1 datum', type: 'text', placeholder: '12 juni 2025', group: 'Artikel 1' },
      { key: 'a2_title', label: 'Artikel 2 titel', type: 'text', placeholder: 'Tips voor betere UX', group: 'Artikel 2' },
      { key: 'a2_date', label: 'Artikel 2 datum', type: 'text', placeholder: '5 juni 2025', group: 'Artikel 2' },
      { key: 'a3_title', label: 'Artikel 3 titel', type: 'text', placeholder: 'Design trends 2025', group: 'Artikel 3' },
      { key: 'a3_date', label: 'Artikel 3 datum', type: 'text', placeholder: '1 juni 2025', group: 'Artikel 3' },
    ],
  },

  {
    type: 'blog',
    variant: 'featured',
    label: 'Featured blog',
    description: 'Groot uitgelicht artikel + 3 secundaire items',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Laatste artikelen' },
      { key: 'a1_title', label: 'Uitgelicht artikel titel', type: 'text', placeholder: 'Het grote verhaal van dit jaar', group: 'Uitgelicht' },
      { key: 'a1_date', label: 'Uitgelicht artikel datum', type: 'text', placeholder: '12 juni 2025', group: 'Uitgelicht' },
    ],
  },

  // FAQ
  {
    type: 'faq',
    variant: 'accordion',
    label: 'FAQ accordion',
    description: 'Veelgestelde vragen uitklapbaar',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Veelgestelde vragen' },
      { key: 'q1', label: 'Vraag 1', type: 'text', placeholder: 'Hoe werkt het?', group: 'Vraag 1' },
      { key: 'a1', label: 'Antwoord 1', type: 'textarea', placeholder: 'Het werkt eenvoudig door...', group: 'Vraag 1' },
      { key: 'q2', label: 'Vraag 2', type: 'text', placeholder: 'Wat zijn de kosten?', group: 'Vraag 2' },
      { key: 'a2', label: 'Antwoord 2', type: 'textarea', placeholder: 'De kosten zijn afhankelijk van...', group: 'Vraag 2' },
      { key: 'q3', label: 'Vraag 3', type: 'text', placeholder: 'Kan ik gratis proberen?', group: 'Vraag 3' },
      { key: 'a3', label: 'Antwoord 3', type: 'textarea', placeholder: 'Ja, je kan 14 dagen gratis proberen.', group: 'Vraag 3' },
    ],
  },

  {
    type: 'faq',
    variant: 'two-column',
    label: 'FAQ twee kolommen',
    description: 'Titel + contact CTA links, accordion rechts',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Veelgestelde vragen' },
      { key: 'cta', label: 'Contact knop', type: 'text', placeholder: 'Stel een vraag' },
      { key: 'q1', label: 'Vraag 1', type: 'text', placeholder: 'Hoe werkt het?', group: 'Vraag 1' },
      { key: 'a1', label: 'Antwoord 1', type: 'textarea', placeholder: 'Het werkt eenvoudig door...', group: 'Vraag 1' },
      { key: 'q2', label: 'Vraag 2', type: 'text', placeholder: 'Wat zijn de kosten?', group: 'Vraag 2' },
      { key: 'a2', label: 'Antwoord 2', type: 'textarea', placeholder: 'De kosten zijn afhankelijk van...', group: 'Vraag 2' },
      { key: 'q3', label: 'Vraag 3', type: 'text', placeholder: 'Kan ik gratis proberen?', group: 'Vraag 3' },
      { key: 'a3', label: 'Antwoord 3', type: 'textarea', placeholder: 'Ja, je kan 14 dagen gratis proberen.', group: 'Vraag 3' },
    ],
  },

  // Contact
  {
    type: 'contact',
    variant: 'split',
    label: 'Contact split',
    description: 'Info links, formulier rechts',
    fields: [
      { key: 'title', label: 'Titel', type: 'text', placeholder: 'Neem contact op' },
      { key: 'subtitle', label: 'Subtitel', type: 'textarea', placeholder: 'We horen graag van je.' },
      { key: 'email', label: 'Email', type: 'text', placeholder: 'info@bedrijf.be' },
      { key: 'phone', label: 'Telefoon', type: 'text', placeholder: '+32 000 00 00 00' },
      { key: 'address', label: 'Adres', type: 'text', placeholder: 'Brussel, België' },
    ],
  },
  {
    type: 'contact',
    variant: 'centered',
    label: 'Gecentreerd contactformulier',
    description: 'Formulier gecentreerd op pagina',
    fields: [
      { key: 'title', label: 'Titel', type: 'text', placeholder: 'Stuur een bericht' },
      { key: 'cta', label: 'Knop tekst', type: 'text', placeholder: 'Versturen' },
    ],
  },

  // Footer
  {
    type: 'footer',
    variant: 'simple',
    label: 'Eenvoudige footer',
    description: 'Logo, links en copyright',
    fields: [
      { key: 'logo', label: 'Logo tekst', type: 'text', placeholder: 'Bedrijfsnaam' },
      { key: 'copyright', label: 'Copyright', type: 'text', placeholder: '© 2025 Bedrijfsnaam. Alle rechten voorbehouden.' },
    ],
  },
  {
    type: 'footer',
    variant: 'multi-column',
    label: 'Multi-kolom footer',
    description: 'Logo, 4 kolommen met links',
    fields: [
      { key: 'logo', label: 'Logo tekst', type: 'text', placeholder: 'Bedrijfsnaam' },
      { key: 'tagline', label: 'Tagline', type: 'text', placeholder: 'Jouw omschrijving hier' },
      { key: 'copyright', label: 'Copyright', type: 'text', placeholder: '© 2025 Bedrijfsnaam.' },
    ],
  },
  {
    type: 'footer',
    variant: 'cta-footer',
    label: 'CTA footer',
    description: 'Blauwe pre-footer CTA balk + donkere footer',
    fields: [
      { key: 'cta_title', label: 'CTA titel', type: 'text', placeholder: 'Klaar om te starten?' },
      { key: 'cta_subtitle', label: 'CTA subtitel', type: 'text', placeholder: 'Neem vandaag nog contact op.' },
      { key: 'cta_primary', label: 'CTA knop tekst', type: 'text', placeholder: 'Begin vandaag' },
      { key: 'logo', label: 'Logo tekst', type: 'text', placeholder: 'Bedrijfsnaam' },
      { key: 'copyright', label: 'Copyright', type: 'text', placeholder: '© 2025 Bedrijfsnaam.' },
    ],
  },

  // Restaurant
  {
    type: 'restaurant',
    variant: 'gallery',
    label: 'Restaurant galerij',
    description: 'Masonry fotogalerij (standaard)',
    fields: [
      { key: 'title', label: 'Titel', type: 'text', placeholder: 'Onze sfeer' },
    ],
  },
  {
    type: 'restaurant',
    variant: 'menu',
    label: 'Menu overzicht',
    description: 'Categorietabs + gerechtenraster met prijs en tags',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Ons menu' },
      { key: 'subtitle', label: 'Subtitel', type: 'text', placeholder: 'Verse ingrediënten, elke dag bereid.' },
      { key: 'cat1_label', label: 'Categorie 1', type: 'text', placeholder: 'Starters', group: 'Categorieën' },
      { key: 'cat2_label', label: 'Categorie 2', type: 'text', placeholder: 'Mains', group: 'Categorieën' },
      { key: 'cat3_label', label: 'Categorie 3', type: 'text', placeholder: 'Desserts', group: 'Categorieën' },
      { key: 'cat4_label', label: 'Categorie 4', type: 'text', placeholder: 'Dranken', group: 'Categorieën' },
      { key: 'cat5_label', label: 'Categorie 5', type: 'text', placeholder: 'Wijnen', group: 'Categorieën' },
      { key: 'item1_price', label: 'Gerecht 1 prijs', type: 'text', placeholder: '€14', group: 'Gerecht 1' },
      { key: 'item1_tag1', label: 'Gerecht 1 tag 1', type: 'text', placeholder: 'Vegan', group: 'Gerecht 1' },
      { key: 'item1_tag2', label: 'Gerecht 1 tag 2', type: 'text', placeholder: 'GF', group: 'Gerecht 1' },
      { key: 'item2_price', label: 'Gerecht 2 prijs', type: 'text', placeholder: '€18', group: 'Gerecht 2' },
      { key: 'item3_price', label: 'Gerecht 3 prijs', type: 'text', placeholder: '€12', group: 'Gerecht 3' },
      { key: 'item3_tag1', label: 'Gerecht 3 tag', type: 'text', placeholder: 'Popular', group: 'Gerecht 3' },
      { key: 'item4_price', label: 'Gerecht 4 prijs', type: 'text', placeholder: '€22', group: 'Gerecht 4' },
      { key: 'cta', label: 'Knop tekst', type: 'text', placeholder: 'Volledig menu' },
    ],
  },
  {
    type: 'restaurant',
    variant: 'specials',
    label: 'Dagschotel / specials',
    description: 'Split layout met chef\'s dagspecial',
    fields: [
      { key: 'badge', label: 'Badge tekst', type: 'text', placeholder: 'Dagschotel' },
      { key: 'title', label: 'Titel', type: 'text', placeholder: 'Chef\'s aanbeveling' },
      { key: 'subtitle', label: 'Subtitel', type: 'text', placeholder: 'Speciaal bereid door onze chef.' },
      { key: 'price', label: 'Prijs', type: 'text', placeholder: '€28' },
      { key: 'ing1', label: 'Ingredient 1', type: 'text', placeholder: 'Ingredient 1', group: 'Ingrediënten' },
      { key: 'ing2', label: 'Ingredient 2', type: 'text', placeholder: 'Ingredient 2', group: 'Ingrediënten' },
      { key: 'ing3', label: 'Ingredient 3', type: 'text', placeholder: 'Ingredient 3', group: 'Ingrediënten' },
      { key: 'cta', label: 'Knop tekst', type: 'text', placeholder: 'Bestellen' },
    ],
  },
  {
    type: 'restaurant',
    variant: 'reservation',
    label: 'Reservatieformulier',
    description: 'Tafelreservatie met datum, tijd en personen',
    fields: [
      { key: 'title', label: 'Titel', type: 'text', placeholder: 'Reserveer een tafel' },
      { key: 'cta', label: 'Knop tekst', type: 'text', placeholder: 'Reserveer nu' },
    ],
  },
  {
    type: 'restaurant',
    variant: 'hours',
    label: 'Openingsuren',
    description: 'Openingstijden + kaart placeholder',
    fields: [
      { key: 'hours_title', label: 'Openingsuren titel', type: 'text', placeholder: 'Openingsuren' },
      { key: 'day1_label', label: 'Dag 1 label', type: 'text', placeholder: 'Maandag – vrijdag', group: 'Openingsuren' },
      { key: 'day2_label', label: 'Dag 2 label', type: 'text', placeholder: 'Zaterdag', group: 'Openingsuren' },
      { key: 'day3_label', label: 'Dag 3 label', type: 'text', placeholder: 'Zondag', group: 'Openingsuren' },
      { key: 'day3_status', label: 'Dag 3 status', type: 'text', placeholder: 'Gesloten', group: 'Openingsuren' },
      { key: 'address_title', label: 'Adres titel', type: 'text', placeholder: 'Adres' },
      { key: 'address', label: 'Adres', type: 'text', placeholder: 'Kerkstraat 12, Gent' },
    ],
  },
  {
    type: 'restaurant',
    variant: 'reviews',
    label: 'Restaurant reviews',
    description: 'Totaalscore + 3 reviewkaarten',
    fields: [
      { key: 'title', label: 'Titel', type: 'text', placeholder: 'Wat onze gasten zeggen' },
    ],
  },
  {
    type: 'restaurant',
    variant: 'delivery',
    label: 'Bezorging & afhaling',
    description: 'Bezorging vs afhalen split CTA',
    fields: [
      { key: 'delivery_title', label: 'Bezorging titel', type: 'text', placeholder: 'Bezorging aan huis', group: 'Bezorging' },
      { key: 'delivery_cta', label: 'Bezorging knop', type: 'text', placeholder: 'Bestel nu', group: 'Bezorging' },
      { key: 'pickup_title', label: 'Afhaling titel', type: 'text', placeholder: 'Afhalen in restaurant', group: 'Afhaling' },
      { key: 'pickup_cta', label: 'Afhaling knop', type: 'text', placeholder: 'Reserveer', group: 'Afhaling' },
    ],
  },

  // Hotel
  {
    type: 'hotel',
    variant: 'packages',
    label: 'Hotel arrangementen',
    description: '2 pakketkaarten met afbeelding en prijs (standaard)',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Speciale arrangementen' },
      { key: 'p1_name', label: 'Pakket 1 naam', type: 'text', placeholder: 'Weekendarrangement', group: 'Pakket 1' },
      { key: 'p1_price', label: 'Pakket 1 prijs', type: 'text', placeholder: '€199', group: 'Pakket 1' },
      { key: 'p1_badge', label: 'Pakket 1 badge', type: 'text', placeholder: 'Weekend Deal', group: 'Pakket 1' },
      { key: 'p2_name', label: 'Pakket 2 naam', type: 'text', placeholder: 'Romantisch pakket', group: 'Pakket 2' },
      { key: 'p2_price', label: 'Pakket 2 prijs', type: 'text', placeholder: '€349', group: 'Pakket 2' },
      { key: 'p2_badge', label: 'Pakket 2 badge', type: 'text', placeholder: 'Honeymoon', group: 'Pakket 2' },
    ],
  },
  {
    type: 'hotel',
    variant: 'rooms',
    label: 'Kamers overzicht',
    description: '3 kamerkaarten met beschikbaarheid en prijs',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Onze kamers' },
      { key: 'r1_name', label: 'Kamer 1 naam', type: 'text', placeholder: 'Standaard kamer', group: 'Kamer 1' },
      { key: 'r1_price', label: 'Kamer 1 prijs', type: 'text', placeholder: '€120', group: 'Kamer 1' },
      { key: 'r1_badge', label: 'Kamer 1 badge', type: 'text', placeholder: 'Beschikbaar', group: 'Kamer 1' },
      { key: 'r1_cta', label: 'Kamer 1 knop', type: 'text', placeholder: 'Boek', group: 'Kamer 1' },
      { key: 'r2_name', label: 'Kamer 2 naam', type: 'text', placeholder: 'Suite', group: 'Kamer 2' },
      { key: 'r2_price', label: 'Kamer 2 prijs', type: 'text', placeholder: '€220', group: 'Kamer 2' },
      { key: 'r2_badge', label: 'Kamer 2 badge', type: 'text', placeholder: 'Suite', group: 'Kamer 2' },
      { key: 'r2_cta', label: 'Kamer 2 knop', type: 'text', placeholder: 'Boek', group: 'Kamer 2' },
      { key: 'r3_name', label: 'Kamer 3 naam', type: 'text', placeholder: 'Budget kamer', group: 'Kamer 3' },
      { key: 'r3_price', label: 'Kamer 3 prijs', type: 'text', placeholder: '€85', group: 'Kamer 3' },
      { key: 'r3_badge', label: 'Kamer 3 badge', type: 'text', placeholder: 'Beperkt', group: 'Kamer 3' },
      { key: 'r3_cta', label: 'Kamer 3 knop', type: 'text', placeholder: 'Boek', group: 'Kamer 3' },
    ],
  },
  {
    type: 'hotel',
    variant: 'amenities',
    label: 'Faciliteiten',
    description: '4x2 icoonraster met faciliteiten',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Onze faciliteiten' },
      { key: 'subtitle', label: 'Subtitel', type: 'text', placeholder: 'Alles voor een zorgeloos verblijf.' },
    ],
  },

  // Marketplace
  {
    type: 'marketplace',
    variant: 'seller-buyer',
    label: 'Kopen & verkopen',
    description: 'Dubbele CTA split voor koper en verkoper (standaard)',
    fields: [
      { key: 'sell_title', label: 'Verkopen titel', type: 'text', placeholder: 'Verkopen', group: 'Verkopen' },
      { key: 'sell_cta', label: 'Verkopen knop', type: 'text', placeholder: 'Advertentie plaatsen', group: 'Verkopen' },
      { key: 'buy_title', label: 'Kopen titel', type: 'text', placeholder: 'Kopen', group: 'Kopen' },
      { key: 'buy_cta', label: 'Kopen knop', type: 'text', placeholder: 'Advertenties bekijken', group: 'Kopen' },
    ],
  },
  {
    type: 'marketplace',
    variant: 'listings',
    label: 'Advertentieraster',
    description: '3-kolom kaarten met tags, prijs en sterren',
    fields: [
      { key: 'l1_price', label: 'Advertentie 1 prijs', type: 'text', placeholder: '€4.500', group: 'Advertentie 1' },
      { key: 'l1_tag1', label: 'Advertentie 1 tag 1', type: 'text', placeholder: '2019', group: 'Advertentie 1' },
      { key: 'l1_tag2', label: 'Advertentie 1 tag 2', type: 'text', placeholder: '45.000 km', group: 'Advertentie 1' },
      { key: 'l1_tag3', label: 'Advertentie 1 tag 3', type: 'text', placeholder: 'Diesel', group: 'Advertentie 1' },
      { key: 'l2_price', label: 'Advertentie 2 prijs', type: 'text', placeholder: '€12.900', group: 'Advertentie 2' },
      { key: 'l2_badge', label: 'Advertentie 2 badge', type: 'text', placeholder: 'Uitgelicht', group: 'Advertentie 2' },
      { key: 'l2_tag1', label: 'Advertentie 2 tag 1', type: 'text', placeholder: '2021', group: 'Advertentie 2' },
      { key: 'l2_tag2', label: 'Advertentie 2 tag 2', type: 'text', placeholder: '18.000 km', group: 'Advertentie 2' },
      { key: 'l2_tag3', label: 'Advertentie 2 tag 3', type: 'text', placeholder: 'Elektrisch', group: 'Advertentie 2' },
      { key: 'l3_price', label: 'Advertentie 3 prijs', type: 'text', placeholder: '€7.200', group: 'Advertentie 3' },
      { key: 'l3_tag1', label: 'Advertentie 3 tag 1', type: 'text', placeholder: '2017', group: 'Advertentie 3' },
      { key: 'l3_tag2', label: 'Advertentie 3 tag 2', type: 'text', placeholder: '82.000 km', group: 'Advertentie 3' },
      { key: 'l3_tag3', label: 'Advertentie 3 tag 3', type: 'text', placeholder: 'Benzine', group: 'Advertentie 3' },
    ],
  },
  {
    type: 'marketplace',
    variant: 'search-filters',
    label: 'Zoeken met filters',
    description: 'Zijbalk filters + lijstresultaten',
    fields: [
      { key: 'cta', label: 'Filter knop', type: 'text', placeholder: 'Filter toepassen' },
      { key: 'r1_price', label: 'Resultaat 1 prijs', type: 'text', placeholder: '€8.500', group: 'Resultaat 1' },
      { key: 'r1_cta', label: 'Resultaat 1 knop', type: 'text', placeholder: 'Bekijken', group: 'Resultaat 1' },
      { key: 'r2_price', label: 'Resultaat 2 prijs', type: 'text', placeholder: '€14.200', group: 'Resultaat 2' },
      { key: 'r2_cta', label: 'Resultaat 2 knop', type: 'text', placeholder: 'Bekijken', group: 'Resultaat 2' },
      { key: 'r3_price', label: 'Resultaat 3 prijs', type: 'text', placeholder: '€5.900', group: 'Resultaat 3' },
      { key: 'r3_cta', label: 'Resultaat 3 knop', type: 'text', placeholder: 'Bekijken', group: 'Resultaat 3' },
    ],
  },
  {
    type: 'marketplace',
    variant: 'categories',
    label: 'Categorieënoverzicht',
    description: '4x2 categorieveraster',
    fields: [
      { key: 'title', label: 'Sectietitel', type: 'text', placeholder: 'Blader per categorie' },
      { key: 'subtitle', label: 'Subtitel', type: 'text', placeholder: 'Vind wat je zoekt.' },
    ],
  },
]

export function getComponentDef(type: string, variant: string): ComponentDefinition | undefined {
  return COMPONENTS.find((c) => c.type === type && c.variant === variant)
}

export function getComponentsByType(type: ComponentType): ComponentDefinition[] {
  return COMPONENTS.filter((c) => c.type === type)
}
